/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `+e2u_album`;
CREATE TABLE `+e2u_album` (
  `id` int NOT NULL,
  `isPrivate` tinyint(1) NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `+e2u_album_film`;
CREATE TABLE `+e2u_album_film` (
  `filmId` int NOT NULL,
  `albumId` int NOT NULL,
  KEY `filmId` (`filmId`),
  KEY `albumId` (`albumId`),
  CONSTRAINT `+e2u_album_film_ibfk_1` FOREIGN KEY (`filmId`) REFERENCES `+e2u_film` (`id`),
  CONSTRAINT `+e2u_album_film_ibfk_2` FOREIGN KEY (`albumId`) REFERENCES `+e2u_album` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `+e2u_film`;
CREATE TABLE `+e2u_film` (
  `id` int NOT NULL,
  `API_ID` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `+e2u_user`;
CREATE TABLE `+e2u_user` (
  `id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `+e2u_user_album`;
CREATE TABLE `+e2u_user_album` (
  `userId` int NOT NULL,
  `albumId` int NOT NULL,
  KEY `userId` (`userId`),
  KEY `albumId` (`albumId`),
  CONSTRAINT `+e2u_user_album_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `+e2u_user` (`id`),
  CONSTRAINT `+e2u_user_album_ibfk_2` FOREIGN KEY (`albumId`) REFERENCES `+e2u_album` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;












/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;